version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: "weekly"
    day: saturday
    time: "21:00"
    timezone: Europe/Amsterdam
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    day: saturday
    time: "21:00"
    timezone: Europe/Amsterdam
 
