language: ruby

rvm:
  - 2.1

cache: 
  - bundler

gemfile: travisGemfile

install: bundle install

script: jekyll build && scss-lint ./_sass/ && htmlproof ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
