language: ruby

sudo: false

rvm:
  - 2.1

cache:
  - bundler

gemfile: travisGemfile

install:
  - bundle install
  - bundle exec scss-lint -v

before_script:
  # -

script:
  - bundle exec jekyll build
  - bundle exec scss-lint $SASS_FOLDER
  - bundle exec htmlproof $HTML_FOLDER --check-favicon --verbose --check-html
  #- bundle exec htmlproof $HTML_FOLDER --check-favicon --verbose --check-html --only_4xx


after_script:
  # - jshint $JS_FOLDER
  # - csslint $CSS_FILES --exclude-list=$CSS_EXCLUDES

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
    - HTML_FOLDER="./_site/"
    - SASS_FOLDER="./_sass/"
    - JS_FOLDER="./js/"
    - CSS_FILES="css/main.css,css/old-ie.css,css/print.css,css/screen.css"
    - CSS_EXCLUDES=""

notifications:
  email: false
