language: ruby

sudo: false

rvm:
  - 2.1

cache: 
  - bundler

gemfile: travisGemfile

install: 
  - bundle install
  - bundle exec scss-lint -v
  # - npm install htmlhint jshint csslint

before_script:
  # - 

script: 
  # - bundle exec sass --check $SASS_FOLDER/*.scss
  - bundle exec jekyll build
  - bundle exec scss-lint $SASS_FOLDER
  - bundle exec htmlproof $HTML_FOLDER --favicon --verbose

after_script:
  # - htmlhint $HTML_FOLDER
  # - jshint $JS_FOLDER
  # - csslint $CSS_FILES --exclude-list=$CSS_EXCLUDES

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
    - HTML_FOLDER="./_site/"
    - SASS_FOLDER="./_sass/"
    - JS_FOLDER="./js/"
    - CSS_FILES="css/main.css,css/old-ie.css,css/print.css,css/screen.css"
    - CSS_EXCLUDES=""

notifications:
  email: false
