language: ruby

rvm:
  - 2.1

cache: 
  - bundler

gemfile: travisGemfile

install: bundle install

script: jekyll build && htmlproof ./_site --href_ignore www.geonovum.nl,eur-lex.europa.eu --favicon --verbose && scss-lint ./_sass/

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
