language: ruby

cache: bundler

gemfile: TravisGemfile

rvm:
  - 2.1

install: bundler install

script: jekyll build && htmlproof ./_site && scss-lint ./_sass/

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
