language: ruby

rvm:
  - 2.1

cache: 
  - bundler

gemfile: travisGemfile

install: 
  - bundle install
  # - npm install htmlhint jshint

script: 
  - jekyll build
  - scss-lint $SASS_FOLDER
  - htmlproof $HTML_FOLDER --favicon --verbose

after_script:
  # - htmlhint $HTML_FOLDER
  # - jshint $JS_FOLDER

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
    - HTML_FOLDER="./_site/"
    - SASS_FOLDER="./_sass/"
    - JS_FOLDER="./js/"

notifications:
  email: false
