#config
markdown:    redcarpet
pygments:    false
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
future:      true
exclude:
  - .notes
  - Gemfile.lock
  - Gemfile

name:        GeoDienstenCentrum i/o

# profile data
author:         GeoDienstenCentrum
site-twitter:   GeoDiensten
author-twitter: mc_prins
# email:          github@
# phone:          nul-zes
github:         GeoDienstenCentrum
url:            http://www.geodienstencentrum.nl
baseurl: 

