# github config override:
# safe: true
lsi: false
# pygments: true
# source: your top-level directory
# see: https://help.github.com/articles/using-jekyll-with-pages

# config, see: http://jekyllrb.com/docs/configuration/
markdown:       redcarpet
pygments:       true
source:         .
destination:    ./_site
plugins:        ./_plugins
layouts:        ./_layouts
future:         true
show_drafts:    nil
exclude:
  - .notes
  - Gemfile.lock
  - Gemfile
include:        []

timezone:       Europe/Amsterdam
  
permalink:      /blog/:categories/:year-:month-:day/:title.html
relative_permalinks: false
paginate:       5
paginate_path:  /blog/page:num

name:           GeoDienstenCentrum
subtitle:       Toegankelijke ruimtelijke dienstverlening

# profile data
author:         GeoDienstenCentrum
site-twitter:   GeoDiensten
author-twitter: mc_prins
email:          github@
phone:          +31 6 0000 0000
github:         GeoDienstenCentrum
url:            http://www.geodienstencentrum.nl
adres: 
  straat:         straatnaam 1
  postcode:       0000AA
  plaatsnaam:     plaatsnaam
  land:           Nederland