# github config override:
# safe: true
# lsi: false
# pygments: true
# source: your top-level directory
# see: https://help.github.com/articles/using-jekyll-with-pages

# config
markdown:    redcarpet
pygments:    false
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
future:      true
exclude:
  - .notes
  - Gemfile.lock
  - Gemfile

name:        GeoDienstenCentrum i/o
subtitle:    Toegankelijke ruimtelijke dienstverlening

# profile data
author:         GeoDienstenCentrum
site-twitter:   GeoDiensten
author-twitter: mc_prins
email:          github@
phone:          +31 6 0000 0000
github:         GeoDienstenCentrum
url:            http://www.geodienstencentrum.nl
