# github config override:
# safe: true
# lsi: false
# pygments: true
# source: your top-level directory
# see: https://help.github.com/articles/using-jekyll-with-pages

# config
markdown:    redcarpet
pygments:    true
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
future:      true
exclude:
  - .notes
  - Gemfile.lock
  - Gemfile

name:        GeoDienstenCentrum i/o
subtitle:    Toegankelijke ruimtelijke dienstverlening

# profile data
author:         GeoDienstenCentrum
site-twitter:   GeoDiensten
author-twitter: mc_prins
email:          github@
phone:          +31 6 0000 0000
github:         GeoDienstenCentrum
url:            http://www.geodienstencentrum.nl

#blurps voor de tag index pagina's
tagblurp:
  pdok:       |
    <abbr title="Publieke Dienstverlening Op de Kaart">PDOK</abbr> 
    biedt een ruime keus aan digitale geo-informatie van de overheid.
  geotools:   |
    <a href="http://geotools.org">GeoTools</a> is een open source Java bibliotheek met programma 
    bouwstenen voor ruimtelijke data.
  openlayers: |
    <a href="http://openlayers.org">OpenLayers</a> is een open source Javascript bibliotheek met programma 
    bouwstenen voor interactieve web cartografie.
