# github config override:
# safe: true
lsi: false
# pygments: true
# source: your top-level directory
# see: https://help.github.com/articles/using-jekyll-with-pages

# config, see: http://jekyllrb.com/docs/configuration/
markdown:       redcarpet
pygments:       true
source:         .
destination:    ./_site
plugins:        ./_plugins
layouts:        ./_layouts
future:         true
show_drafts:    nil
exclude:
  - .notes
  - Gemfile.lock
  - Gemfile
include:        [_pages]

production:     true

timezone:       Europe/Amsterdam
  
permalink:      /blog/:categories/:year-:month-:day/:title.html
relative_permalinks: false
paginate:       5
paginate_path:  /blog/page:num

name:           GeoDienstenCentrum
subtitle:       Toegankelijke ruimtelijke informatievoorziening

# profile data
author:         GeoDienstenCentrum
site-twitter:   GeoDiensten
author-twitter: mc_prins
email:          mark@geodienstencentrum.nl
phone:          
github:         GeoDienstenCentrum
url:            http://www.geodienstencentrum.nl
kvk:            59932953
adres: 
  straat:         Henrica van Erpweg 53
  postcode:       3732 BC
  plaatsnaam:     De Bilt
  land:           Nederland


