# github config override:
# safe: true
lsi: false
# source: your top-level directory
# see: https://help.github.com/articles/using-jekyll-with-pages
# config, see: http://jekyllrb.com/docs/configuration/

plugins:
  - jekyll-sitemap
  - jekyll-paginate
markdown:       kramdown
kramdown:
  input: GFM
source:         .
destination:    ./_site
plugins_dir:    ./_plugins
layouts_dir:    ./_layouts
future:         true
show_drafts:    nil
exclude:
  - .notes
  - Gemfile.lock
  - Gemfile
  - vendor
  - travisGemfile
  - travisGemfile.lock
include:        [_pages]
TZ:             Europe/Amsterdam

production:     true

timezone:       Europe/Amsterdam

permalink:      /blog/:categories/:year-:month-:day/:title.html
relative_permalinks: false
paginate:       5
paginate_path:  /blog/page:num

name:           GeoDienstenCentrum Blog
subtitle:       Over toegankelijke ruimtelijke informatievoorziening

# profile data
author:         GeoDienstenCentrum
site-twitter:   GeoDiensten
author-twitter: mc_prins
email:          mprins@users.sf.net
phone:
github-user:    GeoDienstenCentrum
url:            https://geodienstencentrum.github.io
